config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  
  resources :themes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'index', to: 'homes#index'
  get 'introcurso', to: 'homes#curso'
  get 'introfinal', to: 'homes#final'
  get 'about', to: 'homes#about'
  get 'download_pdf', to: 'homes#downloadCurso', as: 'download_pdf_curso'
  get 'download_pdf', to: 'homes#downloadFinal', as: 'download_pdf_final'



  get 'login', to: 'users_session#new'
  post 'login', to: 'users_session#create'
  post 'logout', to: 'users_session#destroy', as: :logout
  #delete 'logout' => 'users_session#destroy', as: :destroy_current_user_users_session

  get 'register', to: 'users_registration#new'
  post 'register', to: 'users_registration#create'

  get 'producto_cursadas', to: 'cursadas#indexProducts'
  get 'producto_cursadas/:id', to: 'cursadas#showProduct'

  get 'producto_finals', to: 'finals#indexProducts'
  get 'producto_finals/:id', to: 'finals#showProduct'

  resources :password_resets, only: [:create, :edit, :update,:new]
  scope :admin do
    resources :users, only: [:index,:update,:destroy]
    resources :cursadas do
      resources :cursada_contents
    end
    resources :finals, path: 'final' do
      resources :final_contents
    end
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: %i[ show edit update destroy ]

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully created." }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully updated." }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy

    respond_to do |format|
      format.html { redirect_to themes_url, notice: "Theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:title, :description)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_with(model: theme) do |form| %>
  <% if theme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
        <% theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/themes/_theme.html.erb
<div id="<%= dom_id theme %>">
  <p>
    <strong>Title:</strong>
    <%= theme.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= theme.description %>
  </p>

</div>

app/views/themes/edit.html.erb
<h1>Editing theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Show this theme", @theme %> |
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Themes</h1>
<button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" data-bs-title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>
<div id="themes">
  <% @themes.each do |theme| %>
    <%= render theme %>
    <p>
      <%= link_to "Show this theme", theme %>
    </p>
  <% end %>
</div>

<%= link_to "New theme", new_theme_path %>

app/views/themes/new.html.erb
<h1>New theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @theme %>

<div>
  <%= link_to "Edit this theme", edit_theme_path(@theme) %> |
  <%= link_to "Back to themes", themes_path %>

  <%= button_to "Destroy this theme", @theme, method: :delete %>
</div>