config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  
  resources :themes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'index', to: 'homes#index'
  get 'introcurso', to: 'homes#curso'
  get 'introfinal', to: 'homes#final'
  get 'about', to: 'homes#about'
  get 'download_pdf', to: 'homes#downloadCurso', as: 'download_pdf_curso'
  get 'download_pdf', to: 'homes#downloadFinal', as: 'download_pdf_final'



  get 'login', to: 'users_session#new'
  post 'login', to: 'users_session#create'
  post 'logout', to: 'users_session#destroy', as: :logout
  #delete 'logout' => 'users_session#destroy', as: :destroy_current_user_users_session

  get 'register', to: 'users_registration#new'
  post 'register', to: 'users_registration#create'

  get 'producto_cursadas', to: 'cursadas#indexProducts'
  get 'producto_cursadas/:id', to: 'cursadas#showProduct'

  get 'producto_finals', to: 'finals#indexProducts'
  get 'producto_finals/:id', to: 'finals#showProduct'

  resources :password_resets, only: [:create, :edit, :update,:new]
  scope :admin do
    resources :users, only: [:index,:update,:destroy]
    resources :cursadas do
      resources :cursada_contents
    end
    resources :finals, path: 'final' do
      resources :final_contents
    end
  end
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<div id="footer-wrapper">
  <div id="footer" class="container">
    <header class="major">
      <p>FisiologiabyValen</p>
    </header>
    <div class="row">
      <section class="col-12 col-12-narrower">
        <div class="row gtr-0">
          <ul class="divided icons col-12 col-12-mobile" style="text-align: center;">
            <li class="icon brands fa-instagram">
            <a href="https://www.instagram.com/fisiologiabyvalen" target="_blank">
              <i class="fa-brands fa-instagram fa-2xl"></i> Instagram
            </a>
            </li>
            <li class="icon brands fa-whatsapp">
              <a href="https://api.whatsapp.com/send?phone=5492216252514&text=Hola%20Valen!%20Me%20quiero%20sumar%20al%20curso%20de%20acompa%C3%B1amiento%20de%20cursada%2C%20me%20pasas%20el%20cbu%20o%20el%0Aalias%3F%20Gracias" target="_blank">
                <i class="fa-brands fa-whatsapp fa-2xl"></i> Whatsapp
              </a>
            </li>
            <li class="icon brands fa-instagram">
              <a href="https://www.tiktok.com/@fisiologiabyvalen" target="_blank">
                <i class="fa-brands fa-tiktok fa-2xl"></i> Tiktok
              </a>
            </li>
          </ul>
          <ul class="divided icons col-12 col-12-mobile" style="text-align: center;">
            <li class="icon brands">
              <p>Diseño, Desarrollo y Programador <a href="https://portfolio-gp7q0fyut-bottassijuanignacio.vercel.app/"> Juan Ignacio Bottassi</a></p>
            </li>
          </ul>
        </div>
      </section>
    </div>
  </div>
</div>

</div>

app/views/shared/_navbar.html.erb
<div id="header-wrapper">
  <div id="header" class="container menu-navbar">
    <h1 id="logo">
      <%= link_to 'Valen', root_path%>
    </h1>
    <nav id="nav">
      <ul class="navbar-list">
        <% if logged_in? %>
          <li><%= button_to 'Cerrar Sesión', logout_path, method: :post, class:"btn_as_link" %><li>
        <% else %>
          <li><%= button_to 'Iniciar Sesión', login_path, method: :get, class:"btn_as_link" %><li>
        <% end %>
        <% if current_user && current_user.role == "administrador" %>
          <li>
            <%= button_to "Admin", users_path, method: :get, class: "btn_as_link" %>
          </li>
        <% end %>
        <% if current_user && current_user.cursada == true %>
          <li>  
            <%= button_to "Cursada", product_cursadas_path, method: :get, class: "btn_as_link" %>
          </li>
        <% end %>
        <% if current_user && current_user.final == true %>
          <li>
            <%= button_to "Final", product_finals_path, method: :get, class: "btn_as_link" %>
          </li>
        <% end %>
        <li><%= button_to 'Acompañamiento de cursada', introcurso_path, method: :get, class:"btn_as_link" %></li>
        <li><%= button_to 'Curso de final', introfinal_path, method: :get, class:"btn_as_link" %></li>
        <li><%= button_to 'Sobre Mí', about_path, method: :get, class:"btn_as_link" %></li>
      </ul>
    </nav>
  </div>
</div>