config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  
  resources :themes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'index', to: 'homes#index'
  get 'introcurso', to: 'homes#curso'
  get 'introfinal', to: 'homes#final'
  get 'about', to: 'homes#about'
  get 'download_pdf', to: 'homes#downloadCurso', as: 'download_pdf_curso'
  get 'download_pdf', to: 'homes#downloadFinal', as: 'download_pdf_final'



  get 'login', to: 'users_session#new'
  post 'login', to: 'users_session#create'
  post 'logout', to: 'users_session#destroy', as: :logout
  #delete 'logout' => 'users_session#destroy', as: :destroy_current_user_users_session

  get 'register', to: 'users_registration#new'
  post 'register', to: 'users_registration#create'

  get 'producto_cursadas', to: 'cursadas#indexProducts'
  get 'producto_cursadas/:id', to: 'cursadas#showProduct'

  get 'producto_finals', to: 'finals#indexProducts'
  get 'producto_finals/:id', to: 'finals#showProduct'

  resources :password_resets, only: [:create, :edit, :update,:new]
  scope :admin do
    resources :users, only: [:index,:update,:destroy]
    resources :cursadas do
      resources :cursada_contents
    end
    resources :finals, path: 'final' do
      resources :final_contents
    end
  end
end

app/models/cursada.rb
class Cursada < ApplicationRecord
  has_many :cursada_contents, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/cursadas_controller.rb
class CursadasController < ApplicationController
  include Pagy::Backend
  include Pundit::Authorization

  def index
    authorize Cursada
    @cursadas = Cursada.all
    @pagy, @cursadas = pagy(Cursada.all)
  end

  def indexProducts
    authorize Cursada
    @cursadas = Cursada.all
  end

  def show
    authorize Cursada
    @cursada = Cursada.find(params[:id])

    @pagy, @cursada_content = pagy(CursadaContent.all)
  end

  def showProduct
    authorize Cursada
    @cursada = Cursada.find(params[:id])
  end

  def new
    authorize Cursada
    @cursada = Cursada.new
  end

  def create
    authorize Cursada
    @cursada = Cursada.new(cursada_params)

    if @cursada.save
      redirect_to @cursada
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize Cursada
    @cursada = Cursada.find(params[:id])
  end

  def update
    authorize Cursada
    @cursada = Cursada.find(params[:id])

    if @cursada.update(cursada_params)
      redirect_to @cursada
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize Cursada
    @cursada = Cursada.find(params[:id])
    @cursada.destroy

    redirect_to cursadas_path, status: :see_other
  end

  private

  def cursada_params
    params.require(:cursada).permit(:title, :description, :text)
  end
end

app/views/cursadas/_form.html.erb
<div >
  <%= form_with model: @cursada do |f| %>
    
    <div class="form-group div_card">
      <%= f.label 'Titulo' %><br>
      <%= f.text_field :title, class:"form-control" %>
      <% @cursada.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    
    <div class="form-group div_card">
      <%= f.label 'Link del archivo' %><br>
      <%= f.text_field :text, class:"form-control" %>
      <% @cursada.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group div_card">
      <%= f.label 'Descripción' %><br>
      <%= f.text_area :description, class:"form-control" %><br>
      <% @cursada.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="div_card">
      <%= f.submit class:"btn btn-primary" %>
    </div>
  <% end %>

</div>
<br>

app/views/cursadas/edit.html.erb
<div id="admin_form">
    <br>
    <h1 class="title_admin"> Editar tema </h1>
    
    <%= render "form", cursada: @cursada %>

</div>

app/views/cursadas/index.html.erb
<div id="admin_container_cursadas">
  <h1 class="title_admin" style="text-align: center; padding: 125px 15px 0px;;">Acompañamiento de Cursada</h1>
  <div class="link_new_theme">
    <p class="link_new_theme"><%= link_to "Nuevo Tema", new_cursada_path, class: "btn btn-warning mb-2" %></p>
    <p class="link_new_theme"><%= link_to "Final", finals_path, class: "btn btn-warning mb-2" %></p>
    <p class="link_new_theme"><%= link_to "Usuarios", users_path, class: "btn btn-warning mb-2" %></p>
  </div>
  <div class="table-responsive">
    <table id="cursada_table" class="table table-bordered table-hover">
      <thead>
        <tr>
          <th class="pink-background">Título</th>
          <th class="pink-background">Descripción</th>
          <th class="pink-background">Editar</th>
          <th class="pink-background">Eliminar</th>
        </tr>
      </thead>
      <tbody>
        <% @cursadas.each do |cursada| %>
          <tr>
            <td><%= link_to cursada.title, cursada_path(cursada) %></td>
            <td><%= cursada.description %></td>
            <td><%= link_to "Editar", edit_cursada_path(cursada), class: "btn btn-success" %></td>
            <td><%= link_to "Eliminar", cursada_path(cursada), data: { turbo_method: :delete, turbo_confirm: "¿Estás seguro?" }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="pag-bar mt-5 pt-5 d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy)%>
  </div>
</div>

app/views/cursadas/indexProducts.html.erb
<div id="admin_container">
    <br>
    <h1 class="title_admin" style="text-align: center; padding: 125px 15px 0px;;">Acompañamiento de Cursada</h1>
    <br>
        <% @cursadas.each do |cursada| %>
            <div class="card text-center admin_card" >
                <div class="card-body">
                    <h5 class="card-title"><%= link_to cursada.title, producto_cursadas_content_path(cursada) %></h5>
                    <p class="card-text"><%= raw cursada.text %></p>
                    <p class="card-text"><%= cursada.description %></p>
                </div>
            </div>
            <br>
        <% end %>

</div>
<br>

app/views/cursadas/new.html.erb
<div id="admin_form">
    
    <h1 class="title_admin"> Nuevo tema </h1>
    
    <%= render "form", cursada: @cursada %>

</div>

app/views/cursadas/show.html.erb
<div id="admin_container">
  <h2 class="subtitle">Contenido de la Cursada</h2>
  <br>
  <div class="link_new_theme" style="text-align: center;">
    <p class="link_new_theme"><%= link_to "Cursadas", cursadas_path, class: "btn btn-warning mb-2" %></p>
  </div>  
  <br>
  <div class="card text-center admin_card">
    <div class="card-body">
      <h5 class="card-title"><%= @cursada.title %></h5>
      <p class="card-text"><%= raw @cursada.text %></p>
      <p class="card-text"><%= raw @cursada.description %></p>

      
      <%= link_to "Editar", edit_cursada_path(@cursada), class:"btn btn-success" %>
      <%= link_to "Eliminar", cursada_path(@cursada), data: {
        turbo_method: :delete,
        turbo_confirm: "Estas seguro?"
      }, class:"btn btn-danger" %>
    </div>
  </div>
    
  <h2 class="subtitle">Contenido :</h2>
  <%= render @cursada.cursada_contents %>
  
  <h2 class="subtitle">Agregar Contenido :</h2>
  <%= render 'cursada_contents/form' %>

</div>

app/views/cursadas/showProduct.html.erb
<div id="cursada_container">
  <br>
  <h1 class="title_admin" style="text-align: center; padding: 125px 15px 0px;">Contenido del Acompañamiento de Cursada</h1>
  <br>
  <div class="card text-center cursada_card">
    <div class="card-body">
      <h5 class="card-title"><%= @cursada.title %></h5>
      <p class="card-text"><%= raw @cursada.description %></p>
      <p class="card-text"><%= raw @cursada.text %></p>
    </div>
  </div>
    
  
  <h2  class="cursada_subtitle">Contenido</h2>
  <div class="div_card_container">
    <br />
    <% @cursada.cursada_contents.each do |cursada_contents| %>
      <div class="card text-center div_card_children">
        <div class="card-body">
          <strong>Titulo:</strong>
          <h5 class="card-title"><%= cursada_contents.title %></h5>
          <strong>Texto:</strong>
          <h5 class="card-title"><%= raw cursada_contents.text %></h5>
          <strong>Descripción:</strong>
          <p class="card-text"><%= raw cursada_contents.description %></p>
        </div>
      </div>
    <% end %>
    <br />
  </div>
</div>