config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  
  resources :themes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'index', to: 'homes#index'
  get 'introcurso', to: 'homes#curso'
  get 'introfinal', to: 'homes#final'
  get 'about', to: 'homes#about'
  get 'download_pdf', to: 'homes#downloadCurso', as: 'download_pdf_curso'
  get 'download_pdf', to: 'homes#downloadFinal', as: 'download_pdf_final'



  get 'login', to: 'users_session#new'
  post 'login', to: 'users_session#create'
  post 'logout', to: 'users_session#destroy', as: :logout
  #delete 'logout' => 'users_session#destroy', as: :destroy_current_user_users_session

  get 'register', to: 'users_registration#new'
  post 'register', to: 'users_registration#create'

  get 'producto_cursadas', to: 'cursadas#indexProducts'
  get 'producto_cursadas/:id', to: 'cursadas#showProduct'

  get 'producto_finals', to: 'finals#indexProducts'
  get 'producto_finals/:id', to: 'finals#showProduct'

  resources :password_resets, only: [:create, :edit, :update,:new]
  scope :admin do
    resources :users, only: [:index,:update,:destroy]
    resources :cursadas do
      resources :cursada_contents
    end
    resources :finals, path: 'final' do
      resources :final_contents
    end
  end
end

app/models/final.rb
class Final < ApplicationRecord
  has_many :final_contents, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/finals_controller.rb
class FinalsController < ApplicationController
  include Pagy::Backend
  include Pundit::Authorization

  def index
    authorize Final
    @finals = Final.all
    @pagy, @finals = pagy(Final.all)
  end

  def indexProducts
    authorize Final
    @finals = Final.all
  end

  def show
    authorize Final
    @final = Final.find(params[:id])

    @pagy, @final_content = pagy(FinalContent.all)
  end

  def showProduct
    authorize Final
    @final = Final.find(params[:id])
  end

  def new
    authorize Final
    @final = Final.new
  end

  def create
    authorize Final
    @final = Final.new(final_params)

    if @final.save
      redirect_to @final
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize Final
    @final = Final.find(params[:id])
  end

  def update
    authorize Final
    @final = Final.find(params[:id])

    if @final.update(final_params)
      redirect_to @final
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize Final
    @final = Final.find(params[:id])
    @final.destroy

    redirect_to finals_path, status: :see_other
  end

  private

  def final_params
    params.require(:final).permit(:title, :description, :text)
  end
end

app/helpers/finals_helper.rb
module FinalsHelper
end

app/views/finals/_form.html.erb
<div >
  <%= form_with model: @final do |f| %>
    
    <div class="form-group div_card">
      <%= f.label 'Titulo' %><br>
      <%= f.text_field :title, class:"form-control" %>
      <% @final.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    
    <div class="form-group div_card">
      <%= f.label 'Link del archivo' %><br>
      <%= f.text_field :text, class:"form-control" %>
      <% @final.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group div_card">
      <%= f.label 'Descripción' %><br>
      <%= f.text_area :description, class:"form-control" %><br>
      <% @final.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="div_card">
      <%= f.submit class:"btn btn-primary" %>
    </div>
  <% end %>

</div>
<br>

app/views/finals/edit.html.erb
<div id="admin_form">
    <br>
    <h1 class="title_admin"> Editar tema </h1>
    
    <%= render "form", final: @final %>

</div>

app/views/finals/index.html.erb
<div id="admin_final_container">
  <h1 class="title_admin" style="padding: 125px 15px 0px;">Final</h1>
  <div class="link_new_theme">
    <p class="link_new_theme"><%= link_to "Nuevo Tema", new_final_path, class: "btn btn-primary mb-2" %></p>
    <p class="link_new_theme"><%= link_to "Cursadas", cursadas_path, class: "btn btn-primary mb-2" %></p>
    <p class="link_new_theme"><%= link_to "Usuarios", users_path, class: "btn btn-primary mb-2" %></p>
  </div>
  <div class="table-responsive">
    <table id="final_table" class="table table-bordered table-hover">
      <thead>
        <tr>
          <th class="pink-background">Título</th>
          <th class="pink-background">Descripción</th>
          <th class="pink-background">Editar</th>
          <th class="pink-background">Eliminar</th>
        </tr>
      </thead>
      <tbody>
        <% @finals.each do |final| %>
          <tr>
            <td><%= link_to final.title, final_path(final) %></td>
            <td><%= final.description %></td>
            <td><%= link_to "Editar", edit_final_path(final), class: "btn btn-success" %></td>
            <td><%= link_to "Eliminar", final_path(final), data: { turbo_method: :delete, turbo_confirm: "¿Estás seguro?" }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="pag-bar mt-5 pt-5 d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy)%>
  </div>
</div>

app/views/finals/indexProducts.html.erb
<div id="admin_container">
  <br>
  <h1 class="title_admin" style="text-align: center; padding: 125px 15px 0px;;">Curso de Final</h1>
  <br>  
        <% @finals.each do |final| %>
            <div class="card text-center admin_card" >
                <div class="card-body">
                    <h5 class="card-title"><%= link_to final.title, producto_finals_content_path(final) %></h5>
                    <p class="card-text"><%= raw final.text %></p>
                    <p class="card-text"><%= final.description %></p>
                </div>
            </div>
            <br>
        <% end %>

</div>
<br>

app/views/finals/new.html.erb
<div id="admin_form">
    
    <h1 class="title_admin"> Nuevo tema </h1>
    
    <%= render "form", final: @final %>

</div>

app/views/finals/show.html.erb
<div id="admin_container">
  <h2 class="subtitle">Contenido del Final</h2>
  <br>
  <div class="link_new_theme" style="text-align: center; padding-top: 55px;">
    <p class="link_new_theme"><%= link_to "Final", finals_path, class: "btn btn-warning mb-2" %></p>
  </div> 
  <br>
  <div class="card text-center admin_card">
    <div class="card-body">
      <h5 class="card-title"><%= @final.title %></h5>
      <p class="card-text"><%= raw @final.text %></p>
      <p class="card-text"><%= raw @final.description %></p>

      
      <%= link_to "Editar", edit_final_path(@final), class:"btn btn-success" %>
      <%= link_to "Eliminar", final_path(@final), data: {
        turbo_method: :delete,
        turbo_confirm: "Estas seguro?"
      }, class:"btn btn-danger" %>
    </div>
  </div>
    
  <h2 class="subtitle">Contenido :</h2>
  <%= render @final.final_contents %>
  
  <h2 class="subtitle">Agregar Contenido :</h2>
  <%= render 'final_contents/form' %>
  
</div>

app/views/finals/showProduct.html.erb
<div id="final_container">
  <br>
  <h1 class="title_admin" style="text-align: center; padding: 125px 15px 0px;;">Contenido del Final</h1>
  <br>
  <div class="card text-center final_card">
    <div class="card-body">
      <h5 class="card-title"><%= @final.title %></h5>
      <p class="card-text"><%= raw @final.description %></p>
      <p class="card-text"><%= raw @final.text %></p>
    </div>
  </div>
    
  
  <h2  class="final_subtitle">Contenido</h2>
  <div class="div_card_container">
    <br />
    <% @final.final_contents.each do |final_contents| %>
      <div class="card text-center div_card_children">
        <div class="card-body">
          <strong>Titulo:</strong>
          <h5 class="card-title"><%= final_contents.title %></h5>
          <strong>Texto:</strong>
          <h5 class="card-title"><%= raw final_contents.text %></h5>
          <strong>Descripción:</strong>
          <p class="card-text"><%= raw final_contents.description %></p>
        </div>
      </div>
    <% end %>
    <br />
  </div>
</div>